### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by 0neday** [ryanh7/ha-nmc-weather#1]
```
Logger: homeassistant.helpers.integration_platform
Source: loader.py:583
First occurred: 17:57:38 (7 occurrences)
Last logged: 17:57:38

Unexpected error importing nmc_weather/system_health.py
Unexpected error importing nmc_weather/media_source.py
Unexpected error importing nmc_weather/logbook.py
Unexpected error importing nmc_weather/cast.py
Unexpected error importing nmc_weather/energy.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 34, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 566, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 583, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.nmc_weahter.recorder'
```

**Comment by ryanh7** [comment]
无法重现你的日志
